Variables and data types
danacebryantalfonso/udemyActivities pull request #1
Opened 2021-03-16 08:45 UTC by danacebryantalfonso

Changed the folder name and added the exercise 2 and 3.

2021-03-16 10:16 UTC, rexendy-lig requested changes

2021-03-16 10:16 UTC, rexendy-lig commented on Strings and Data Types/src/StringsAndFunctions.kt
> +class StringsAndDataTypes:Exercises(){
apply spacing
ex.
class StringsAndDataTypes : Exercises() {

2021-03-16 10:16 UTC, rexendy-lig commented on Strings and Variables/.idea/.gitignore
> +/workspace.xml
apply necessary classes/folders in .gitignore
ex.
include .idea in .gitingore

2021-03-17 00:59 UTC, danacebryantalfonso commented on Strings and Data Types/src/StringsAndFunctions.kt
> +class StringsAndDataTypes:Exercises(){
Fixed this in d4a2890da6f59994e6561d5e61d373d29eee2be0

2021-03-17 01:04 UTC, danacebryantalfonso commented on Strings and Variables/src/Exercise1.kt
> +//    println(url)
comment removed in c578ba0a0cd5f71366ca440d9af87f911997d170

2021-03-17 01:05 UTC, danacebryantalfonso commented on Strings and Data Types/src/StringsAndFunctions.kt
> +class StringsAndDataTypes:Exercises(){
Added spaces after closing braces in c578ba0a0cd5f71366ca440d9af87f911997d170

2021-03-17 01:41 UTC, danacebryantalfonso commented on Strings and Variables/.idea/.gitignore
> +/workspace.xml
Added those folders and files in 07953db5071a9a2074d902bae929c099b1638636

2021-03-17 01:59 UTC, merged

2021-03-17 01:59 UTC, rexendy-lig approved these changes