Android coroutines retrofit mvvm
danacebryantalfonso/udemyActivities pull request #12
Opened 2021-03-25 08:13 UTC by danacebryantalfonso

2021-03-26 04:32 UTC, rexendy-lig requested changes

2021-03-26 04:32 UTC, rexendy-lig commented on AndroidCoroutinesRetrofitMVVM/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/countriesList"
Dan pls use snake case
ex. countries_list

2021-03-26 04:32 UTC, rexendy-lig commented on AndroidCoroutinesRetrofitMVVM/app/src/main/res/layout/item_country.xml
> +            android:layout_width="0dp"
same here
in all xml, pls use snake case

2021-03-26 04:32 UTC, rexendy-lig commented on AndroidCoroutinesRetrofitMVVM/build.gradle
> +        classpath 'com.android.tools.build:gradle:4.1.3'
psl create a def for the versions
ex. def gradle_version = '4.1.3'
 classpath "com.android.tools.build:gradle:$gradle_version"

2021-03-26 04:32 UTC, rexendy-lig commented on AndroidCoroutinesRetrofitMVVM/app/src/main/java/com/devtides/androidcoroutinesretrofit/view/CountryListAdapter.kt
> +    fun updateCountries(newCountries: List<Country>) {
use arrayListOf inseaed of ArrayList
use listOf instead of List

2021-03-26 04:32 UTC, rexendy-lig commented on AndroidCoroutinesRetrofitMVVM/app/src/main/java/com/devtides/androidcoroutinesretrofit/view/CountryListAdapter.kt
> +import android.view.ViewGroup
pls use android.view.*

pls use .* if same ra ang packages

2021-03-26 08:36 UTC, danacebryantalfonso commented on AndroidCoroutinesRetrofitMVVM/app/src/main/java/com/devtides/androidcoroutinesretrofit/view/CountryListAdapter.kt
> +    fun updateCountries(newCountries: List<Country>) {
Correct me if I'm wrong, can't do this arrayListOf and listOf because the variable used is dynamic and it is directly called to a model Country class.
 
I can only do like this:
![Screen Shot 2021-03-26 at 4 28 50 PM](https://user-images.githubusercontent.com/80668751/112603961-a1528600-8e50-11eb-9ec0-919db284f1ef.png)

2021-03-26 08:44 UTC, rexendy-lig commented on AndroidCoroutinesRetrofitMVVM/app/src/main/java/com/devtides/androidcoroutinesretrofit/view/CountryListAdapter.kt
> +    fun updateCountries(newCountries: List<Country>) {
Dan pls check this code. 
class CountryListAdapter(var countries: arrayListOf<Country>()): RecyclerView.Adapter<CountryListAdapter.CountryViewHolder>() {

    fun updateCountries(newCountries: listOf<Country>()) {

2021-03-26 08:46 UTC, danacebryantalfonso commented on AndroidCoroutinesRetrofitMVVM/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/countriesList"
revised in e1499e3be5f5358edbdf74ac013316da6e3e4ec3

2021-03-26 08:46 UTC, danacebryantalfonso commented on AndroidCoroutinesRetrofitMVVM/app/src/main/res/layout/item_country.xml
> +            android:layout_width="0dp"
revised in e1499e3be5f5358edbdf74ac013316da6e3e4ec3

2021-03-26 08:46 UTC, danacebryantalfonso commented on AndroidCoroutinesRetrofitMVVM/app/src/main/res/layout/item_country.xml
> +            android:layout_width="0dp"
revised in e1499e3be5f5358edbdf74ac013316da6e3e4ec3

2021-03-26 08:51 UTC, danacebryantalfonso commented on AndroidCoroutinesRetrofitMVVM/build.gradle
> +        classpath 'com.android.tools.build:gradle:4.1.3'
revised in e1499e3be5f5358edbdf74ac013316da6e3e4ec3
is it ok, if I did this way? 
ext {
        gradle_version = '4.1.3'
        kotlin_version = '1.3.61'
    }
so that it can be changed in the project variables.
If not I'm just going to do like this
def gradle_version = '4.1.3'
ext.kotlin_version = '1.3.61'

2021-03-26 08:52 UTC, danacebryantalfonso commented on AndroidCoroutinesRetrofitMVVM/app/src/main/java/com/devtides/androidcoroutinesretrofit/view/CountryListAdapter.kt
> +import android.view.ViewGroup
revised in e1499e3be5f5358edbdf74ac013316da6e3e4ec3

2021-03-26 09:26 UTC, danacebryantalfonso commented on AndroidCoroutinesRetrofitMVVM/app/src/main/java/com/devtides/androidcoroutinesretrofit/view/CountryListAdapter.kt
> +    fun updateCountries(newCountries: List<Country>) {
still don't work ms rex, I'll try to find some work-around on this

![Screen Shot 2021-03-26 at 5 12 47 PM](https://user-images.githubusercontent.com/80668751/112610867-20978800-8e58-11eb-938a-a71aa6a2ab93.png)

2021-03-26 10:31 UTC, rexendy-lig commented on AndroidCoroutinesRetrofitMVVM/app/src/main/java/com/devtides/androidcoroutinesretrofit/view/CountryListAdapter.kt
> +    fun updateCountries(newCountries: List<Country>) {
`class CountryListAdapter(var countries: arrayListOf<String>()): RecyclerView.Adapter<CountryListAdapter.CountryViewHolder>() {
`

2021-03-26 10:42 UTC, danacebryantalfonso commented on AndroidCoroutinesRetrofitMVVM/app/src/main/java/com/devtides/androidcoroutinesretrofit/view/CountryListAdapter.kt
> +    fun updateCountries(newCountries: List<Country>) {
Still it gives an error ms Rex.
Sorry if I missed something but the only work around I did is
![Screen Shot 2021-03-26 at 6 40 56 PM](https://user-images.githubusercontent.com/80668751/112619916-d962c480-8e62-11eb-9870-f74cc1788d21.png)

2021-03-29 02:42 UTC, rexendy-lig approved these changes

2021-03-29 02:42 UTC, merged