UI testing
danacebryantalfonso/udemyActivities pull request #16
Opened 2021-04-22 08:20 UTC by danacebryantalfonso

my latest activity

2021-04-23 10:12 UTC, rexendy-lig requested changes

2021-04-23 10:12 UTC, rexendy-lig commented on SocialIntegration/app/src/androidTest/java/com/exercise/socialintegration/SocIntTest.kt
> +        onView(withId(R.id.btn_mlogin)).perform(closeSoftKeyboard(),scrollTo(), click())
after you perform a certain function, pls assert something that proves it denies or login successfully
pls apply to other test cases also

2021-04-23 10:12 UTC, rexendy-lig commented on SocialIntegration/app/src/main/java/com/exercise/socialintegration/adapter/UserViewHolder.kt
> +        }*/
remove if not needed

2021-04-23 10:12 UTC, rexendy-lig commented on SocialIntegration/app/src/main/java/com/exercise/socialintegration/ui/signin/SignInFragment.kt
>              }else{
add space after if and {
ex
if () {
} else {
}

2021-04-26 02:55 UTC, danacebryantalfonso commented on SocialIntegration/app/src/androidTest/java/com/exercise/socialintegration/SocIntTest.kt
> +        onView(withId(R.id.btn_mlogin)).perform(closeSoftKeyboard(),scrollTo(), click())
done in b4486f9909e16c5bda5b8c2852ca12b612ca1c9c

2021-04-26 02:55 UTC, danacebryantalfonso commented on SocialIntegration/app/src/main/java/com/exercise/socialintegration/adapter/UserViewHolder.kt
> +        }*/
done in b4486f9909e16c5bda5b8c2852ca12b612ca1c9c

2021-04-26 02:55 UTC, danacebryantalfonso commented on SocialIntegration/app/src/main/java/com/exercise/socialintegration/ui/signin/SignInFragment.kt
>              }else{
done in b4486f9909e16c5bda5b8c2852ca12b612ca1c9c

2021-04-26 04:35 UTC, danacebryantalfonso commented on SocialIntegration/app/src/main/java/com/exercise/socialintegration/ui/signin/SignInFragment.kt
>              }else{
revised in 51259d1a67d2cd5e7b9f436730a9c698e7684308

2021-04-26 05:31 UTC, rexendy-lig approved these changes

2021-04-26 05:32 UTC, merged